name: 2. Destroy Azure K8s Cluster for Compredict GitOps Demo
on:
  workflow_dispatch:

permissions:
      id-token: write                                                                   # Gain permissions
      contents: read
jobs:                                                                                   # Single job name having multiple tasks
  AKS-Cluster-Monitoring:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infrastructure                                               # Run the commands in the "infrastructure" directory where the tf files are present
    steps:
      - name: Checkout                                                                  # Step to do checkout
        uses: actions/checkout@v3.1.0
        
      - name: 'Az CLI login'                                                            # Step that uses SVN OIDC (Open ID Connect based Authentication) to get access to my Azure Subscription
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run az commands'
        run: |
          az account show
          az group list
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: latest
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN_ID }}                    # Terraform cloud Token ID

      - name: Terraform Init                                                           # Step to initialize the working directory and download the necessary provider plugins and modules and set up the backend for storing infrastructure state
        id: init
        run: terraform init
      
      - name: Terraform Validate                                                       # Step to verify the correctness of the Terraform configuration files     
        id: validate
        run: terraform validate

      - name: Terraform Validate Status                                                    # Step to check terraform plan status and exit the process on failure
        if: steps.validate.outcome == 'failure'
        run: exit 1

      - name: Terraform Destroy                                                        # Step to terminate resources defined in the Terraform configuration
        id: destroy
        run: terraform destroy --var="github_token=${{ secrets.TF_VAR_GITHUB_TOKEN }}" --auto-approve

      - name: Azure K8s Cluster config cleanup
        run: |
          rm -rf ~/.kube
